steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-docker.pkg.dev/devops-test-terraform-blue/my-repo/php-fpm-app:latest',
        '.'
      ]
    dir: 'modules/cloud_run'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-docker.pkg.dev/devops-test-terraform-blue/my-repo/php-fpm-app:latest'
      ]

images:
  - 'europe-docker.pkg.dev/devops-test-terraform-blue/my-repo/php-fpm-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY

