name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
  REGION: ${{ secrets.GCLOUD_REGION }}
  SERVICE_NAME: php-fpm-service
  IMAGE_NAME: php-fpm-app
  GCR_HOSTNAME: ${{ secrets.GCR_HOSTNAME }}

jobs:
  build-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        # Récupère le code source du repo

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          export_default_credentials: true
        # Installe et authentifie le CLI gcloud avec le compte de service

      - name: Run PHP unit tests
        run: |
          composer install
          ./vendor/bin/phpunit tests
        # Lance les tests unitaires PHP pour valider le code avant build

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker ${{ env.GCR_HOSTNAME }}
        # Configure Docker pour pouvoir push sur Google Container Registry

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.GCR_HOSTNAME }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest .
        # Construit l’image Docker à partir du Dockerfile

      - name: Push Docker Image to GCR
        run: |
          docker push ${{ env.GCR_HOSTNAME }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
        # Pousse l’image vers Google Container Registry

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.GCR_HOSTNAME }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated
        # Déploie l’image sur Cloud Run, rend le service accessible publiquement

